name: 'HTTP Request Action'
description: 'Create any HTTP Request'
inputs:
    repertoire:
        description: 'Répertoire'
        required: true
    method:
        description: 'Request Method'
        required: false
        default: 'QA'
outputs:
    response:
        description: 'HTTP Response Content'
    headers:
        description: 'HTTP Response Headers'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/DeploiementFRW.ps1 -sourceDir ${{ inputs.repertoire }} 
      shell: pwsh