name: 'MTESS - Déployer formulaire web Github Action'
description: 'Une extension simple pour déployer ses formulaires FRW.'
inputs:
    repertoire:
        description: 'Répertoire'
        required: false
        default: '${{ github.workspace }}'
    environnement:
        description: 'QA, PROD, ou url complète'
        required: false
        default: 'QA'
    noPublicSystemeAutorise:
        description: 'Numéro public de système autorisé'
        required: true
    apiKey:
        description: 'Clée API'
        required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/DeploiementFRW.ps1 -sourceDir ${{ inputs.repertoire }} -apiSiteWeb ${{ inputs.environnement }} -noPublicSystemeAutorise ${{ inputs.noPublicSystemeAutorise }} -apiKey ${{ inputs.apiKey }}
      shell: pwsh